### PR TITLE
Update & Add a few things :)

### PR DESCRIPTION
**Pull request by Tringlle**

### CODE REVIEW

**Comment by Tringlle** [comment]
Works fine on mine :-

**Comment by KikoPT1234** [comment]
Seems good, merged

**Comment by KikoPT1234** [comment]
Just a quick heads up, you don't need to manually edit the routes.json file

**Comment by KikoPT1234** [comment]
why'd you remove the plugin list i just noticed

**Comment by Tringlle** [comment]
> why'd you remove the plugin list i just noticed

bc I updated the mh full tutorial page, it supports custom jars now

**Pull request merged**
