### PR TITLE
Update a LOT of files.

### PR DESCRIPTION
**Pull request by Tringlle**
A lot of stuff wasn't updated to the newest mh release, so its updated now :)

If you would like to see the things I changed, here https://minehut-xyz-tringlle.vercel.app/

### CODE REVIEW

**Comment by Tringlle** [comment]
And it all worked on my testing server.

**Comment by Tringlle** [comment]
and yes, I updated it with `plugin-list.js` back

**Comment by Tringlle** [comment]
apparently smth updated so I had to fix that :confused:

**Comment by KikoPT1234** [comment]
deprecated is spelled with an e, could you fix that?

**Comment by Tringlle** [comment]
> deprecated is spelled with an e, could you fix that?

Sure, gime a sec

**Comment by Tringlle** [comment]
There you go

**Comment by Tringlle** [comment]
Im gonna let github check if it actually works, then ill letcha know

**Comment by Tringlle** [comment]
Ight, it works

**Comment by Tringlle** [comment]
Just made `craftenhance.md` easier to read.

**Pull request merged**
